In [1]:
import sys
sys.path.insert(0, '../')

import pandas as pd
import numpy as np

import aimlets.BasicUtils as basicutils

import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display, HTML


%matplotlib inline

basicutils.set_defaults()

In [2]:
data = pd.read_csv('hr-analytics.csv')

basicutils.get_adv_desc_dfs(data);

SHAPE: 14999 ROWS x 10 COLUMNS